// <auto-generated />
namespace streaming_inż.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class changetypeofpublicsong : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changetypeofpublicsong));
        
        string IMigrationMetadata.Id
        {
            get { return "201701162201008_change type of public song"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
