// <auto-generated />
namespace streaming_inż.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeindexfromusertable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeindexfromusertable));
        
        string IMigrationMetadata.Id
        {
            get { return "201701182257273_remove index from user table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
